### PR TITLE
Use recaptcha plugin from Joomla! instead the old way

### PR DESCRIPTION
**Pull request by xillibit**

### CODE REVIEW

**Comment by rich20** [comment]
With CAPTCHA Challenge for Guests and registered users it works. But if you set the captcha only for guests, then registered users see this error.

Notice: Undefined variable: app in /.../plugins/content/kunenadiscuss/kunenadiscuss.php on line 670

Fatal error: Call to a member function redirect() on null in /---/plugins/content/kunenadiscuss/kunenadiscuss.php on line 670

**Comment by xillibit** [comment]
Should be better now

**Comment by rich20** [comment]
- [ ] Failed - is still the same error

**Comment by xillibit** [comment]
I don't have this error, how do-you to have it ?

**Comment by rich20** [comment]
When is set Captcha for Nobody or only for guests. Registered user can't send a message via discuss-plugin.

**Comment by xillibit** [comment]
Try now

**Comment by rich20** [comment]
- [x] Success

**Pull request merged**
