### PR TITLE
Fix for Joomla! 3.5 Captcha in KunenaDiscuss

### PR DESCRIPTION
**Pull request by Ruud68**
Hi, here you go. copied some of the logic from the forum that displayed the captcha correct.
Also made the theme and size take the values from the captcha plugin.
tested on both Joomla 3.4.8 and Joomla 3.5
Hope this helps :)

### CODE REVIEW

**Comment by xillibit** [comment]
You are putting the code into the template which isn't the place for the logic

**Comment by Ruud68** [comment]
in what file should it be put then?

**Comment by xillibit** [comment]
In kunenadiscuss.php

**Comment by Ruud68** [comment]
Okay, that was my first try: putting it into function displayCaptcha(), but if I am not mistaking that function should return a string (according to the comment), but does not return anything and the displaying of the captcha's <div> is currently not via that function but in the template?
Or am I mistaking?
If you point me in the right direction I can have a new go at it :)

**Pull request closed without merging**
