### PR TITLE
Add class to topic and readmore links

### PR DESCRIPTION
**Pull request by Ruud68**
Hi, as discussed and requested here: https://www.kunena.org/forum/kunena-feature-requests/140116-adding-a-class-to-the-content-kunena-discuss-link-in-content

I have added classes on the links and also added a space after the :

hope this helps!

### CODE REVIEW

**Comment by Ruud68** [comment]
Hi @810 could you have a look at this PR? If okay I can delete it from my todo list :)

**Comment by 810** [comment]
will check tomorrow the addons

**Comment by Ruud68** [comment]
Hi, cool. Please also check https://github.com/Kunena/Kunena-Addons/issues/247

I have workaround for KunenaDiscuss, but I think this should be fixed in Kunena itself (no idea how).

**Comment by Tormentor667** [comment]
Is there an estimated time when this will be available in an official release?

**Comment by 810** [comment]
its already in the latest version

**Comment by Tormentor667** [comment]
Strange because it doesn't work for me, check this link and the appropriate "Discuss" link on the page, no "class" attached:
http://realm667.com/index.php/en/home/archiv/75-community-news/1950-reviews-back-online

I am on the latest version of all Kunena plugins and component.

**Comment by 810** [comment]
try clean cache.

Which settings do you have.

**Comment by Tormentor667** [comment]
Cleared the cache, reloaded, didn't help. Which settings do you mean?
http://www.realm667.com/index.php/en/home/archiv/75-community-news/1950-reviews-back-online

**Comment by rich20** [comment]
You have the first 2 links if your setting is "Show on Front Page = Posts".
But your setting is: "Show on Front Page = Links" and that's the third link.
#### Existing Links
- [x] Posts in discussion: class = kdiscuss-topic
- [x] Read more: class = kdiscuss-readmore
- [ ] Discuss this article in the forums: has no own class

**Comment by Tormentor667** [comment]
Thanks for the explanation but can you be a bit more precise? I don't get it where to change what to get the class.

**Comment by rich20** [comment]
Check the setting options in the plugin. Should be "Show on Front Page = Posts".

**Comment by Tormentor667** [comment]
Take a look:
http://realm667.com/index.php/en/home/archiv/75-community-news/1950-reviews-back-online

I changed the setting but now I have two links as well as various moderation buttons, but all I want is just a button to the forum thread that has been created.

Sorry for all this, I simply don't get it.

**Pull request merged**
